
services:

  spring-app:
    container_name: practice-app
    image: "gregory1011/practice-app:v2"
    ports:
      - "9077:8003" # tomcat runs at 8003 and the container will map it 9077 -> http://localhost:9077
    environment:
#      SPRING_PROFILES_ACTIVE: demo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/practice-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: "always"
      SPRING_DEVTOOLS_ADD_PROPERTIES: "true"
      LOGGING_LEVEL_ROOT: "INFO"
      LOGGING_LEVEL_WEB: "WARN"
      LOGGING_LEVEL_SQL: "ERROR"
    depends_on:
      - db
    networks:
      - demo_network
  db:
    container_name: db-practice-app
    image: postgres:latest
    environment:
      POSTGRES_DB: practice-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
     - '5432:5432'
#    command: -p 5432
#    expose:
#      - "5432"
#    ports:
# #     - "5488:5432"  if we want to change it.
#      - "5432:5432"
    networks:
      - demo_network
networks:
  demo_network:
    driver: bridge
